server:
  port: ${SERVER_PORT:8071}
spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:luna}
    password: ${RABBIT_MQ_PASSWORD:luna}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ##password: ${REDIS_PASSWORD:}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/sc_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: ${DATASOURCE_USERNAME:luna}
    password: ${DATASOURCE_PASSWORD:luna}
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    loadbalancer:
      retry:
        enabled: true

logging:
  level:
    org.springframework.web: info
    org.springframework.security: info
    org.apache.ibatis: debug
    java.sql.PreparedStatement: info
  file:
    path: logs/
  logback:
    rolling policy:
      clean-history-on-start: true
      max-history: 7
      max-file-size: 200MB

dubbo:
  application:
    name: spring-dubbo-provider
    logger: slf4j

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
